/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/gate.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Gate(props) {
  const { nodes, materials } = useGLTF('public/models/gate.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[1.617, 0.845, 0]} />
    </group>
  )
}

useGLTF.preload('/gate.glb')
